import numpy as np
import torch
import os
import glob
from tqdm import tqdm

# CONFIGURATION
CHUNKS_DIR = "processed_edges_dict" 
CACHE_DIR  = "cache_spatial" # UPDATED FOLDER

# INPUTS (Generated by main.py and create_spatial_split.py)
PATH_INDICES = os.path.join(CACHE_DIR, "valid_indices.pt")
PATH_MASKS   = os.path.join(CACHE_DIR, "spatial_split_masks.pt")

# OUTPUTS
TRAIN_PATH = os.path.join(CACHE_DIR, "graph_train_edges.pt")
TEST_PATH  = os.path.join(CACHE_DIR, "graph_test_edges.pt")

def split_and_stitch():
    print(f"--- Starting Spatial Split & Stitch ---")
    
    # 1. Load ID Map
    if not os.path.exists(PATH_INDICES):
        print("Error: valid_indices.pt not found. Run main.py first.")
        return
    
    print("Loading ID Map...")
    # valid_indices is a list of Real IDs sorted by their row index
    valid_ids_list = torch.load(PATH_INDICES, weights_only=False)
    
    # We need: Real_ID -> Row_Index
    # Since the list is sorted by Row Index (0..N), we just reverse it.
    # But wait, preprocessing.py sorts them.
    # Let's trust the list order IS the row order.
    
    map_keys = np.array(valid_ids_list, dtype=np.uint64)
    map_vals = np.arange(len(valid_ids_list), dtype=np.int32)
    
    # Sort keys for fast search
    sort_idx = np.argsort(map_keys)
    sorted_keys = map_keys[sort_idx]
    sorted_vals = map_vals[sort_idx]
    
    # 2. Load Spatial Masks
    if not os.path.exists(PATH_MASKS):
        print("Error: Spatial masks not found. Run create_spatial_split.py first.")
        return
        
    masks = torch.load(PATH_MASKS, weights_only=False)
    is_train_neuron = masks['train_mask'].numpy()
    is_test_neuron  = masks['test_mask'].numpy()
    
    print(f"Train Neurons: {is_train_neuron.sum():,}")
    print(f"Test Neurons:  {is_test_neuron.sum():,}")

    # 3. Process Chunks
    npy_files = sorted(glob.glob(os.path.join(CHUNKS_DIR, "edges_dict_part_*.npy")))
    train_edges_list = []
    test_edges_list = []
    
    print(f"Processing {len(npy_files)} chunks...")
    
    for fpath in tqdm(npy_files):
        raw_edges = np.load(fpath)
        if raw_edges.shape[0] == 0: continue
        raw_edges = raw_edges.astype(np.uint64)

        # Map Raw ID -> Row Index
        src_idx = np.searchsorted(sorted_keys, raw_edges[:, 0])
        dst_idx = np.searchsorted(sorted_keys, raw_edges[:, 1])
        
        src_idx = np.clip(src_idx, 0, len(sorted_keys) - 1)
        dst_idx = np.clip(dst_idx, 0, len(sorted_keys) - 1)
        
        src_valid = (sorted_keys[src_idx] == raw_edges[:, 0])
        dst_valid = (sorted_keys[dst_idx] == raw_edges[:, 1])
        valid_mask = src_valid & dst_valid
        
        if not np.any(valid_mask): continue

        valid_src = sorted_vals[src_idx[valid_mask]]
        valid_dst = sorted_vals[dst_idx[valid_mask]]
        
        # --- SPATIAL FILTER ---
        # Train Edge: Both nodes in Train Mask
        train_mask_edge = is_train_neuron[valid_src] & is_train_neuron[valid_dst]
        if np.any(train_mask_edge):
            train_edges_list.append(np.column_stack((valid_src[train_mask_edge], valid_dst[train_mask_edge])))
            
        # Test Edge: Both nodes in Test Mask
        test_mask_edge = is_test_neuron[valid_src] & is_test_neuron[valid_dst]
        if np.any(test_mask_edge):
            test_edges_list.append(np.column_stack((valid_src[test_mask_edge], valid_dst[test_mask_edge])))

    # 4. Save
    print("\nSaving...")
    if train_edges_list:
        full_train = np.concatenate(train_edges_list, axis=0)
        torch.save(torch.from_numpy(full_train).t().contiguous(), TRAIN_PATH)
        print(f"Saved TRAIN: {len(full_train):,} edges")
    
    if test_edges_list:
        full_test = np.concatenate(test_edges_list, axis=0)
        torch.save(torch.from_numpy(full_test).t().contiguous(), TEST_PATH)
        print(f"Saved TEST:  {len(full_test):,} edges")

if __name__ == "__main__":
    split_and_stitch()